# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuzwa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField()),
                ('usability', models.IntegerField()),
                ('creativity', models.IntegerField()),
                ('content', models.IntegerField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design', to='tuzwa.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='project',
        ),
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
        migrations.RemoveField(
            model_name='creativity',
            name='project',
        ),
        migrations.RemoveField(
            model_name='creativity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='design',
            name='project',
        ),
        migrations.RemoveField(
            model_name='design',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usability',
            name='project',
        ),
        migrations.RemoveField(
            model_name='usability',
            name='user',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Creativity',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.DeleteModel(
            name='Usability',
        ),
    ]
